# Generated by Django 5.2.7 on 2025-10-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_remove_content_feature_image_content_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='photo',
        ),
    ]
