# Generated by Django 5.2.7 on 2025-10-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_content_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
    ]
