# Generated by Django 5.2.7 on 2025-10-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_content_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
